version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      -  POSTGRES_PASSWORD=dev_password
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

  hasura:
    image: hasura/graphql-engine:latest
    container_name: hasura
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:dev_password@timescaledb:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # Enable the web console
      HASURA_GRAPHQL_ADMIN_SECRET: dev_admin_secret # Admin secret for secure access
    depends_on:
      - timescaledb
    restart: always

volumes:
  timescaledb_data:
    driver: local
